baseURL = "https://breadtube.tv/"
languageCode = "en-us"
title = "BreadTube"

[ params ]
description = "Quality content going against the prevailing winds of the internet."
targetBlank = true
defaultTags = []

[[ menu.main ]]
name = "Channels"
url = "/"

[[ menu.main ]]
name = "Playlists"
url = "/playlists/"

[[ menu.footer ]]
name = "Discord"
url = "/discord"

[[ menu.footer ]]
name = "Twitter"
url = "/twitter"

[[ menu.footer ]]
name = "Facebook"
url = "/facebook"

[[ menu.footer ]]
name = "Tumblr"
url = "/tumblr"

[[ menu.footer ]]
name = "YouTube"
url = "/youtube"

[[ menu.footer ]]
name = "Github"
url = "/github"
