baseURL = "https://breadtube.tv/"
languageCode = "en-us"
title = "BreadTube"

[ params ]
description = "Quality content going against the prevailing winds of the internet."
logo = "/img/breadtube.png"
targetBlank = true
defaultTags = []

[languages]
  [languages.en]
    title = "BreadTube"
    weight = 1

[[ menu.main ]]
name = "Home"
url = "/"
weight = 1

[[ menu.main ]]
name = "Playlists"
url = "/playlists/"
weight = 2

[[ menu.main ]]
name = "Channels"
url = "/channels/"
weight = 3

[[ menu.main ]]
name = "Videos"
url = "/videos/"
weight = 4

[[ menu.main ]]
name = "Blog"
url = "/blog/"
weight = 5

[[ menu.footer ]]
name = "Discord"
url = "/discord"
weight = 1

[[ menu.footer ]]
name = "Twitter"
url = "/twitter"
weight = 2

[[ menu.footer ]]
name = "YouTube"
url = "/youtube"
weight = 3

[[ menu.footer ]]
name = "Facebook"
url = "/facebook"
weight = 4

[[ menu.footer ]]
name = "Tumblr"
url = "/tumblr"
weight = 5

[[ menu.footer ]]
name = "Github"
url = "/github"
weight = 6
